apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: metallb-system

helmGlobals:
  chartHome: .

helmCharts:
- name: metallb
  valuesFile: metallb/values.yaml
  releaseName: metallb
