# helm repo add longhorn https://charts.longhorn.io
# helm repo update
# helm install longhorn longhorn/longhorn --namespace longhorn-system --create-namespace --version 1.10.1 --values values-longhorn.yaml
# helm upgrade longhorn longhorn/longhorn --namespace longhorn-system --values ./values-longhorn.yaml

longhornUI:
  replicas: 1

